
# Build matrix
language: node_js
matrix:
  include:

    # Run tests in Node.js 0.10
    - node_js: '0.10'

    # Run tests in Node.js 0.12
    - node_js: '0.12'

    # Run tests in Node.js 4.x (dependencies require GCC 4.8)
    - node_js: '4'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Before install
before_install:
  # Use GCC 4.8 if it's available
  - 'if [ ! `which gcc-4.8` == "" ]; then export CXX=g++-4.8 && export CC=gcc-4.8; fi'

# Build script
script:
  - make ci
